#!/bin/bashllsubmit AGT.cmd && 
llsubmit ABT.cmd && 
llsubmit BCD.cmd && 
#!/bin/bashllsubmit AGT.cmd && 
llsubmit ALG.cmd && 
llsubmit BOO.cmd && 
llsubmit CAT.cmd && 
llsubmit COM.cmd && 
llsubmit CSR.cmd && 
llsubmit GEG.cmd && 
llsubmit GEO.cmd && 
llsubmit GRA.cmd && 
llsubmit GRP.cmd && 
llsubmit HAL.cmd && 
llsubmit HWV.cmd && 
llsubmit KLE.cmd && 
llsubmit KRS.cmd && 
llsubmit LAT.cmd && 
llsubmit LCL.cmd && 
llsubmit MED.cmd && 
llsubmit MGT.cmd && 
llsubmit MSC.cmd && 
llsubmit NLP.cmd && 
llsubmit NUM.cmd && 
llsubmit PLA.cmd && 
llsubmit PRO.cmd && 
llsubmit PUZ.cmd && 
llsubmit REL.cmd && 
llsubmit RNG.cmd && 
llsubmit SCT.cmd && 
llsubmit SET.cmd && 
llsubmit SEU.cmd && 
llsubmit SWB.cmd && 
llsubmit SWC.cmd && 
llsubmit SWV.cmd && 
llsubmit SWW.cmd && 
llsubmit SYN.cmd && 
llsubmit SYO.cmd && 
llsubmit TOP.cmd && 
